# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true

vars:
  KIND_CLUSTER_NAME: '{{ .KIND_CLUSTER_NAME | default "agntcy-test" }}'

  ## Image config
  IMAGE_REPO: '{{ .IMAGE_REPO | default "ghcr.io/agntcy" }}'
  DIRECTORY_IMAGE_TAG: '{{ .DIRECTORY_IMAGE_TAG | default "v0.2.0" }}'

  HELM_NAMESPACE: '{{ .HELM_NAMESPACE | default "default" }}'

  REMOVE_CONTAINERS: '{{ .REMOVE_CONTAINERS | default "true" }}'

  RUNNER_TYPE: '{{ .RUNNER_TYPE | default "docker" }}'

  ARCH:
    sh: |
      if [ "$ARCH" == "" ]; then
        uname -m
      else
        printf $ARCH
      fi
  OS:
    sh: |
      if [ "$OS" == "" ]; then
        uname -s
      else
        printf $OS
      fi
  DIRCTL_BIN_PATH:
    sh: |
      if [ "$DIRCTL_BIN_PATH" == "" ]; then
        mkdir -p $PWD/agntcy-dir/tests/.bin
        printf $PWD/tests/.bin
      else
        printf $DIRCTL_BIN_PATH
      fi
  DIRCTL_BIN_VERSION: '{{ .DIRCTL_BIN_VERSION | default "v0.2.0" }}'

tasks:
  k8s:port-forward:setup:
    internal: true
    cmds:
      - kubectl port-forward svc/agntcy-dir-apiserver -n {{ .HELM_NAMESPACE }} 8888 &
      - sleep 1

  k8s:port-forward:teardown:
    internal: true
    cmds:
      - kill -9 $(ps aux | grep port-forward | grep agntcy-dir-apiserver | awk '{print $2}') || true

  test-env:deploy:
    desc: Deploy Agntcy directory test env
    vars:
      REGCRED_CREATE: '{{ .REGCRED_CREATE | default "false" }}'
    cmds:
      - |
        kubectl config use-context kind-{{ .KIND_CLUSTER_NAME }} &&
        helm dependency build ./components/helm
        helm upgrade agntcy-dir \
          ./components/helm \
          --set dir.apiserver.image.tag="{{ .DIRECTORY_IMAGE_TAG }}" \
          --set regcred.create="{{ .REGCRED_CREATE }}" \
          --namespace {{ .HELM_NAMESPACE }} \
          --create-namespace \
          --install \
          --wait \
          --wait-for-jobs \
          --timeout "15m"

  test-env:cleanup:
    desc: Remove agntcy directory test env
    cmds:
      - kubectl config use-context kind-{{ .KIND_CLUSTER_NAME }} &&
      - helm delete --ignore-not-found --namespace {{ .HELM_NAMESPACE }} agntcy-dir

  test:
    desc: All directory test
    cmds:
      - task: k8s:port-forward:setup
      - defer: { task: k8s:port-forward:teardown }
      - defer: { task: manifests:cleanup }
      - REMOVE_CONTAINERS={{.REMOVE_CONTAINERS}} RUNNER_TYPE={{.RUNNER_TYPE}} PATH=$PATH:{{.DIRCTL_BIN_PATH}} IMAGE_REPO={{.IMAGE_REPO}} DIRECTORY_IMAGE_TAG={{.DIRECTORY_IMAGE_TAG}} go test ./tests -v -failfast -test.v -test.paniconexit0 -ginkgo.timeout 30m -timeout 30m -ginkgo.v

  test:compiler:
    desc: Agntcy compiler test
    cmds:
      - docker pull {{.IMAGE_REPO}}/dir-ctl:{{.DIRECTORY_IMAGE_TAG}}
      - REMOVE_CONTAINERS={{.REMOVE_CONTAINERS}} RUNNER_TYPE={{.RUNNER_TYPE}} PATH=$PATH:{{.DIRCTL_BIN_PATH}} IMAGE_REPO={{.IMAGE_REPO}} DIRECTORY_IMAGE_TAG={{.DIRECTORY_IMAGE_TAG}} go test ./tests -v -failfast -test.v -test.paniconexit0 -ginkgo.timeout 10m -timeout 10m -ginkgo.v -ginkgo.focus "agent compilation"

  test:compile:samples:
    desc: Agntcy compiler test in samples
    cmds:
      - docker pull {{.IMAGE_REPO}}/dir-ctl:{{.DIRECTORY_IMAGE_TAG}}
      - REMOVE_CONTAINERS={{.REMOVE_CONTAINERS}} RUNNER_TYPE={{.RUNNER_TYPE}} PATH=$PATH:{{.DIRCTL_BIN_PATH}} IMAGE_REPO={{.IMAGE_REPO}} DIRECTORY_IMAGE_TAG={{.DIRECTORY_IMAGE_TAG}} go test ./tests -v -failfast -test.v -test.paniconexit0 -ginkgo.timeout 10m -timeout 10m -ginkgo.v -ginkgo.focus "Samples build test"

  test:push:
    desc: Directory agent push test
    cmds:
      - task: k8s:port-forward:setup
      - defer: { task: k8s:port-forward:teardown }
      - defer: { task: manifests:cleanup }
      - REMOVE_CONTAINERS={{.REMOVE_CONTAINERS}} RUNNER_TYPE={{.RUNNER_TYPE}} PATH=$PATH:{{.DIRCTL_BIN_PATH}} IMAGE_REPO={{.IMAGE_REPO}} DIRECTORY_IMAGE_TAG={{.DIRECTORY_IMAGE_TAG}} go test ./tests -v -failfast -test.v -test.paniconexit0 -ginkgo.timeout 30m -timeout 30m -ginkgo.v -ginkgo.focus "agent push and pull"

  test:list:
    desc: Directory agent list test
    cmds:
      - task: k8s:port-forward:setup
      - defer: { task: k8s:port-forward:teardown }
      - defer: { task: manifests:cleanup }
      - REMOVE_CONTAINERS={{.REMOVE_CONTAINERS}} RUNNER_TYPE={{.RUNNER_TYPE}} PATH=$PATH:{{.DIRCTL_BIN_PATH}} IMAGE_REPO={{.IMAGE_REPO}} DIRECTORY_IMAGE_TAG={{.DIRECTORY_IMAGE_TAG}} go test ./tests -v -failfast -test.v -test.paniconexit0 -ginkgo.timeout 30m -timeout 30m -ginkgo.v -ginkgo.focus "Agntcy agent list tests"

  download:dirctl-bin:
    desc: Get dirctl binary from GitHub
    vars:
      ARCH:
        sh: |
          printf "%s" "{{.ARCH}}" | \
            sed -E 's/^(aarch64|aarch64_be|armv6l|armv7l|armv8b|armv8l)$$/arm64/g' | \
            sed -E 's/^x86_64$$/amd64/g'
      OS:
        sh: printf "%s" "{{.OS}}" | tr '[:upper:]' '[:lower:]'
    cmds:
      - |
        URL=https://github.com/agntcy/dir/releases/download/{{.DIRCTL_BIN_VERSION}}/dirctl-{{.OS}}-{{.ARCH}}
        echo $URL
        curl \
          --fail \
          --show-error \
          --location $URL \
          --output "{{.DIRCTL_BIN_PATH}}/dirctl" && \
        chmod +x "{{.DIRCTL_BIN_PATH}}/dirctl"

        # NOTE: The attribute may removed already, silent errors
        xattr -d com.apple.quarantine "{{.DIRCTL_BIN_PATH}}/dirctl" &> /dev/null || true
