# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0
# agntcy slim — KinD cluster B, namespace cluster-b
# Controller on cluster A via Ingress host (edge nginx on :80 → KinD :10080). Requires
# `task up:with-ingress-apps` (or equivalent) + macOS `/etc/resolver/csit.test` with `port` = CSIT_LOCAL_DNS_HOST_PORT (default 8053).
# For slim pods on B reaching the host-mapped port from inside the cluster, see
# helm/values/slim-cluster-b.docker-desktop.yaml.
slim:
  replicaCount: 1
  daemonset: false
  image:
    repository: ghcr.io/agntcy/slim
    pullPolicy: IfNotPresent
    tag: ""
  overrideConfig:
    tracing:
      log_level: debug
      display_thread_names: true
      display_thread_ids: true
    runtime:
      n_cores: 0
      thread_name: slim-data-plane
      drain_timeout: 10s
    services:
      slim/0:
        group_name: cluster-b
        dataplane:
          servers:
            - endpoint: "0.0.0.0:46357"
              metadata:
                local_endpoint: ${env:MY_POD_IP}
                external_endpoint: "agntcy-cluster-b-slim.cluster-b.svc.cluster.local:46357"
                trust_domain: example.org
              tls:
                insecure: true
        controller:
          clients:
            - endpoint: "control.cluster-a.csit.test:80"
              tls:
                insecure: true

  ingresses:
    - portName: data-plane-0
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      hosts:
        - host: slim.cluster-b.csit.test
          paths:
            - path: /
              pathType: Prefix

mcpProxy:
  enabled: false
