# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0
# agntcy slim — KinD cluster B, namespace cluster-b
# Controller on cluster A: use CoreDNS peer name (expose northbound on node-a first, e.g. NodePort).
slim:
  replicaCount: 1
  daemonset: false
  image:
    repository: ghcr.io/agntcy/slim
    pullPolicy: IfNotPresent
    tag: ""
  overrideConfig:
    tracing:
      log_level: debug
      display_thread_names: true
      display_thread_ids: true
    runtime:
      n_cores: 0
      thread_name: slim-data-plane
      drain_timeout: 10s
    services:
      slim/0:
        group_name: cluster-b
        dataplane:
          servers:
            - endpoint: "0.0.0.0:46357"
              metadata:
                local_endpoint: ${env:MY_POD_IP}
                external_endpoint: "agntcy-cluster-b-slim.cluster-b.svc.cluster.local:46357"
                trust_domain: example.org
              tls:
                insecure: true
        controller:
          clients:
            - endpoint: "node-a.csit.peer:50051"
              tls:
                insecure: true

mcpProxy:
  enabled: false
