[tool.poetry]
name = "report_crew"
version = "0.1.1"
description = "report template"
authors = ["Catarina Paralta <46568597+paralta@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = ">=3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
