# SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

---
version: "3"

silent: true

tasks:
  dependencies:
    desc: Install dependencies.
    internal: true
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - poetry install

  publish:
    desc: Publish PyPi package in Espresso-PyPi repo (https://engci-maven-master.cisco.com/artifactory/api/pypi/espresso-pypi/)
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - poetry publish --build --repository devhubcloud --verbose
