#!/usr/bin/env bash
# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0
#
# Writes coredns/.gen/peers.env with PEER_A_IP / PEER_B_IP (Docker IPv4 on kind network).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${ROOT}/coredns/.gen"
mkdir -p "${OUT_DIR}"

CLUSTER_A="${CLUSTER_A:-csit-a}"
CLUSTER_B="${CLUSTER_B:-csit-b}"
NET="${KIND_DOCKER_NETWORK:-kind}"

docker_ip() {
  local container="$1"
  if ! docker inspect "$container" >/dev/null 2>&1; then
    echo "ERROR: container not found: $container (is Kind cluster running?)" >&2
    exit 1
  fi
  local ip
  ip=$(docker inspect -f '{{with index .NetworkSettings.Networks "'"${NET}"'"}}{{.IPAddress}}{{end}}' "$container")
  if [[ -z "${ip}" ]]; then
    ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$container" | awk '{print $1; exit}')
  fi
  if [[ -z "${ip}" ]]; then
    echo "ERROR: no IPv4 for $container on network ${NET}" >&2
    exit 1
  fi
  echo "$ip"
}

A_IP=$(docker_ip "${CLUSTER_A}-control-plane")
B_IP=$(docker_ip "${CLUSTER_B}-control-plane")

cat >"${OUT_DIR}/peers.env" <<EOF
# Generated by discover-peer-ips.sh — do not commit
PEER_A_IP=${A_IP}
PEER_B_IP=${B_IP}
CLUSTER_A=${CLUSTER_A}
CLUSTER_B=${CLUSTER_B}
EOF

echo "Wrote ${OUT_DIR}/peers.env"
echo "  ${CLUSTER_A}-control-plane -> ${A_IP}"
echo "  ${CLUSTER_B}-control-plane -> ${B_IP}"
