#!/usr/bin/env bash
# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${ROOT}/optional/with-ingress/dns/Corefile"
ZONE="${CSIT_DNS_ZONE:-csit.test}"
IP_A="${CSIT_INGRESS_IP_A:-127.0.0.1}"
# Both zones point at the host loopback; edge/nginx on :80 routes by Host to each KinD ingress.
IP_B="${CSIT_INGRESS_IP_B:-127.0.0.1}"
UPSTREAM="${CSIT_DNS_UPSTREAM:-1.1.1.1}"
umask 022
cat >"${OUT}" <<EOF
# Generated by render-local-dns-corefile.sh
# CoreDNS Corefile consumed by optional/with-ingress/dns/docker-compose.yaml.
.:53 {
    errors
    # Keep query logs visible in container stdout/stderr.
    log

    # Explicit records used by optional ingress manifests.
    hosts {
        ${IP_A} control.cluster-a.${ZONE}
        ${IP_A} slim.cluster-a.${ZONE}
        ${IP_B} slim.cluster-b.${ZONE}
        fallthrough
    }

    # Catch-all for *.${ZONE} so additional ingress hostnames resolve to loopback.
    template IN A {
        match (.*\\.)?${ZONE//./\\.}\\.
        answer "{{ .Name }} 60 IN A 127.0.0.1"
    }

    # Resolve everything else through upstream DNS.
    forward . ${UPSTREAM}
}
EOF
echo "Wrote ${OUT}"
