#!/usr/bin/env bash
# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${ROOT}/optional/with-ingress/dns/dnsmasq.conf"
ZONE="${CSIT_DNS_ZONE:-csit.test}"
IP_A="${CSIT_INGRESS_IP_A:-127.0.0.1}"
# Both zones point at the host loopback; edge/nginx on :80 routes by Host to each KinD ingress.
IP_B="${CSIT_INGRESS_IP_B:-127.0.0.1}"
UPSTREAM="${CSIT_DNS_UPSTREAM:-1.1.1.1}"
umask 022
cat >"${OUT}" <<EOF
# Generated by render-dnsmasq.sh
no-resolv
server=${UPSTREAM}
listen-address=127.0.0.1
bind-interfaces

address=/cluster-a.${ZONE}/${IP_A}
address=/cluster-b.${ZONE}/${IP_B}
EOF
echo "Wrote ${OUT}"
