# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0
# Both zones → 127.0.0.1; edge/nginx on :80 proxies by Host to KinD (10080 / 9080).
no-resolv
server=1.1.1.1
listen-address=127.0.0.1
bind-interfaces

address=/cluster-a.csit.test/127.0.0.1
address=/cluster-b.csit.test/127.0.0.1
