# Example: KinD B with host port maps for optional edge stack (see README in this folder).
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: csit-b
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 9080
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 443
        hostPort: 9443
        listenAddress: "127.0.0.1"
        protocol: TCP
