topology:
    clients:
        "agentA":
            auth:
                spireJwt: true
            connectedTo:
                - "slim-1"
            image: "ghcr.io/agntcy/slim/python-examples:latest"    
            cmd: ./examples/fire-and-forget.py
            args: ["-m","hello","-i","1000"]
        "agentB":
            auth:
                spireJwt: true
            connectedTo:
                - "slim-2"
            image: "ghcr.io/agntcy/slim/python-examples:latest"    
            cmd: ./examples/fire-and-forget.py
            args: ["-i","1000"]                
    servers:
        "main":
            spireMtls: false
            routes:
                - "agentA > slim-1"
                - "agentA > slim-2"
                - "agentB > slim-1"
                - "agentB > slim-2"
        "slim-1":
            routes:                
                - "agentA > main"
                - "agentB > main"
        "slim-2":
            routes:                
                - "agentA > main"
                - "agentB > main"