topology:
    clients:
        "alice":
            auth:
                spireJwt: true
            connectedTo:
                - "slim-1"
            image: agntcy/slim-python-examples:v0.0.1
            cmd: fire-and-forget.py
            args: ["-m","hello","-i","1000","-l", "cisco/default/alice", "-r", "cisco/default/bob"]
        "bob":
            auth:
                spireJwt: true
            connectedTo:
                - "slim-1"
            image: agntcy/slim-python-examples:v0.0.1
            cmd: fire-and-forget.py
            args: ["-i","1000", "-l", "cisco/default/bob"]
    servers:
        "main":
            spireMtls: false
            routes:
                - "alice > slim-1"
                - "alice > slim-2"
                - "bob > slim-1"
                - "bob > slim-2"
        "slim-1":
            routes:                
                - "alice > main"
                - "bob > main"
        "slim-2":
            routes:                
                - "alice > main"
                - "bob > main"
