# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: Deploy agntcy ADS components
description: Deploy agntcy ADS components
inputs:
  directory-image-tag:
    description: 'Set gateway container image version'
    required: false
    default: 'v0.2.5'
  directory-chart-tag:
    description: 'Set gateway chart version'
    required: false
    default: 'v0.2.5'
  kind-cluster-name:
    description: 'Set kind cluster name where components are deployed'
    required: false
    default: 'agntcy-test'
  kind-cluster-namespace:
    description: 'Set cluster namespace where components are deployed'
    required: false
    default: 'default'

runs:
  using: 'composite'
  steps:
    - name: Create Kind Cluster
      uses: helm/kind-action@v1
      with:
        cluster_name: ${{ inputs.kind-cluster-name }}
        wait: 300s

    - name: deploy agntcy ADS
      shell: bash
      env:
        DIRECTORY_IMAGE_TAG: ${{ inputs.directory-image-tag }}
        DIRECTORY_CHART_TAG: ${{ inputs.directory-chart-tag }}
        KIND_CLUSTER_NAME: ${{ inputs.kind-cluster-name }}
        KIND_CLUSTER_NAMESPACE: ${{ inputs.kind-cluster-namespace }}
      run: |
        kubectl config use-context kind-$KIND_CLUSTER_NAME
        helm upgrade agntcy-ads oci://ghcr.io/agntcy/dir/helm-charts/dir \
          --version $DIRECTORY_CHART_TAG \
          --set image.tag="${DIRECTORY_IMAGE_TAG}" \
          --namespace $KIND_CLUSTER_NAMESPACE \
          --create-namespace \
          --install \
          --wait \
          --wait-for-jobs \
          --timeout "15m"
