# SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

---

name: Setup Environment
description: setup environment with common tools/vars
inputs:
  python:
    description: 'Install python'
    required: false
    default: false
  python-version-1:
    description: 'Python version to install'
    required: false
    default: '3.11'
  python-version-2:
    description: 'Python version to install'
    required: false
    default: '3.12'
  go:
    description: 'Install golang'
    required: false
    default: false
  go-version:
    description: 'Go version to install'
    required: false
    default: '1.23.1'

runs:
  using: "composite"
  steps:
    - name: Setup Taskfile
      shell: bash
      run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

    - name: Setup Python
      if: ${{ inputs.python == 'true' }}
      uses:  ./.github/actions/setup-python
      with:
        py-version-1: ${{ inputs.python-version-1 }}
        py-version-2: ${{ inputs.python-version-2 }}

    - name: Setup Golang
      if: ${{ inputs.go == 'true' }}
      uses: ./.github/actions/setup-go
      with:
        go-version: ${{ inputs.go-version }}

    - name: Update GITHUB_PATH
      shell: bash
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
