topology:
    clusters:
        "cluster-a":
            spireMtls: false
            replicaCount: 1
        "cluster-b":
            spireMtls: false
            replicaCount: 2
        "cluster-c":
            spireMtls: false
            replicaCount: 2
