# SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sum
  namespace: llama-deploy-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sum
  template:
    metadata:
      labels:
        app: sum
    spec:
      containers:
        - name: sum
          env:
            - name: WORKFLOW_HOST
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: WORKFLOW_SUM_HOST
            - name: WORKFLOW_PORT
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: WORKFLOW_SUM_PORT
            - name: WORKFLOW_INTERNAL_HOST
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: WORKFLOW_SUM_INTERNAL_HOST
            - name: WORKFLOW_INTERNAL_PORT
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: WORKFLOW_SUM_INTERNAL_PORT
            - name: SIMPLE_MESSAGE_QUEUE_HOST
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: SIMPLE_MESSAGE_QUEUE_HOST
            - name: SIMPLE_MESSAGE_QUEUE_PORT
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: SIMPLE_MESSAGE_QUEUE_PORT
            - name: SIMPLE_MESSAGE_QUEUE_INTERNAL_HOST
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: SIMPLE_MESSAGE_QUEUE_INTERNAL_HOST
            - name: SIMPLE_MESSAGE_QUEUE_INTERNAL_PORT
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: SIMPLE_MESSAGE_QUEUE_INTERNAL_PORT
            - name: CONTROL_PLANE_HOST
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: CONTROL_PLANE_HOST
            - name: CONTROL_PLANE_PORT
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: CONTROL_PLANE_PORT
            - name: CONTROL_PLANE_INTERNAL_HOST
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: CONTROL_PLANE_INTERNAL_HOST
            - name: CONTROL_PLANE_INTERNAL_PORT
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: CONTROL_PLANE_INTERNAL_PORT 
          image: sum:latest
          imagePullPolicy: Never
          command:
            [
              "sh",
              "-c", 
              "poetry run python -m llama_sum.deploy_sum",
            ]
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sum
  name: sum
  namespace: llama-deploy-demo
spec:
  selector:
    app: sum
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000