# SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'release/')}}

jobs:
  prepare-build:
    name: Prepare Build
    outputs:
      targets: ${{ steps.all-targets.outputs.targets }}
      image-tag: ${{ steps.resolve.outputs.image_tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          python: false
          go: false

      - name: Container image
        id: resolve
        run: |
          # Export vars
          echo "image_tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: List all targets
        id: all-targets
        uses: docker/bake-action/subaction/list-targets@a4d7f0b5b91c14a296d792d4ec53a9db17f02e67 # v5.5.0
        with:
          workdir: ./integrations/agntcy-agp/agentic-apps

  build-push:
    name: Build docker image - ${{ matrix.target }}
    needs: [prepare-build]
    if: ${{ needs.prepare-build.outputs.targets != '[]' && needs.prepare-build.outputs.targets != '' }}
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.prepare-build.outputs.targets) }}
    uses: ./.github/workflows/reusable-docker-build-push.yaml
    permissions:
      contents: 'read'
      packages: 'write'
      attestations: 'write'
    with:
      bake-target: ${{ matrix.target }}
      image-name: ${{ matrix.target }}
      image-tag: ${{ needs.prepare-build.outputs.image-tag }}
      workdir: ./integrations/agntcy-agp/agentic-apps
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

